### ISSUE TITLE
isbn and bibtexkey

### ISSUE THREAD

**Issue by sammo3182** [Vopaaz/CNKI_2_BibTeX#1]
Thank you so much for offering this amazing software! It works pretty well and straightfoward. A quick suggestion, though, in the current version (6f6aeb41827b1a80fb315f740003db5a5777a74e), the output always includes a `isbn/issn` line. You know, `/` often causes issues for some programming or editing languages (e.g., markdown). Is it possible to just using `issn` instead of `isbn/issn` in the output? 

Another suggestion: the default bibtexkey now is the Pinyin of the title, right? They sometimes could be long, unreadable, and distractive, esp. when adding multiple entries in a paper. Can I ask for some other format for the key, e.g., name-year? (Jabref uses such way to create keys, the output is something like `Lee2009`, while giving the characteristics of Chinese last names, a full name paper might be more proper, such as `Sunwukong1986`).

**Comment by Vopaaz** [comment]
I'm currently travelling so the improvement may be somehow delayed, but I will try to fix these problems as soon as possible. Thank you for offering such great suggestions!

**Comment by Vopaaz** [comment]
@sammo3182 
I've updated version `0.2.0` on PyPI, (6d34374a2b8b4ce692f31621f1caf2db2452f545 on GitHub). Please use `pip install --upgrade cnki2bib` to acquire the latest version.
- Two fields, each called "ISBN" and "ISSN", will be generated if an "ISBN/ISSN" field is provided in the ".net" source file. I believe this solved the `/` problem while saving more information.
- Now you can use the `-f nameyear` option to set the key format. The configuration will be saved so you only have to do it once.

Thank you again for your suggestions!

**Comment by sammo3182** [comment]
Amazing! The new update works pretty well! Thank you for the prompt update.
