### ISSUE TITLE
BibTeX entries copied to clipboard seems not to work as expected

### ISSUE THREAD

**Issue by liyc-ai** [Vopaaz/CNKI_2_BibTeX#6]
Hi, i am just using the `cnki2bib` in terminal after copying the NoteExpress-style reference to the clipboard. It gave me some output as below:

```shell
Read the NoteExpress Entry content from the clipboard.
BibTeX entries copied to clipboard.
File 'out.bib' is created at current directory.
```

And there was `out.bib` file in my current directory, in which the content is what i want. But it seems that the `BibTex entries copied to clipboard`  not work, and the bibTex-style reference was not copied to the clipboard.

My os is `Ubuntu 19.10`, and the python version is 3.7.0. Thanks!

**Comment by Vopaaz** [comment]
The functionality works well on my Win10 machine, so it looks like some OS compatibility issue, which is out of the scope of this application. We used the [pyperclip](https://github.com/asweigart/pyperclip) module to handle cross-platform, clipboard events.

Would you please test the following commands?

Firstly `pip install pyperclip`, then in the Python REPL:

```python
>>> import pyperclip
>>> pyperclip.copy("aaa")
```

After that, `aaa` should be in your clipboard.

If this did not work, according to the documents of pyperclip:

> On Linux, this module makes use of the xclip or xsel commands, which should come with the os. Otherwise run "sudo apt-get install xclip" or "sudo apt-get install xsel" (Note: xsel does not always seem to work.)

If the above-mentioned test still failed, I suggest that you raise an issue to pyperclip. Thanks!

**Comment by liyc-ai** [comment]
Thanks! `sudo apt-get install xclip` works!
