### ISSUE TITLE
希望能增加覆盖原来的out.bib文件或者继续写入文件的选项

### ISSUE THREAD

**Issue by KeyToon9** [Vopaaz/CNKI_2_BibTeX#7]
每次运行后都会覆盖原来的out.bib文件，希望能增加一个选项，让脚本在已有的文件上继续写入而不是新建覆盖。

**Comment by Vopaaz** [comment]
最近有点忙，预计几个月之内加下这个功能。

--- 

I've been a little busy these days. The feature will be implemented within a couple of months.
