### ISSUE TITLE
转换结果文献类型不对

### ISSUE THREAD

**Issue by krisfans** [Vopaaz/CNKI_2_BibTeX#9]
转化为bib文件的参考文献标识不对
比如这里从知网导出一篇硕士论文，他的`.net`文件如下
```txt
{Reference Type}: Thesis
{Author}: 宋开军
{Year}: 2007
{Title}: 基于波导的微波毫米波空间功率合成技术研究
{URL}: https://kns.cnki.net/kcms/detail/detail.aspx?dbname=CDFD2007&filename=2007101113.nh&dbcode=CDFD
{Date}: 2007-03-01
{Journal}: 电子科技大学
{Issue}: 04
{Pages}: 129-130
{Keywords}: 空间功率合成技术;同轴波导;径向波导;基片集成波导;毫米波
{DOI}: CNKI:CDMD:1.2007.101113
```
通过`cnki2bib.exe`转换成`.bib`后结果如下
```bibtex
@Misc{jiyubodaode,
	author = {宋开军},
	year = {2007},
	title = {基于波导的微波毫米波空间功率合成技术研究},
	url = {https://kns.cnki.net/kcms/detail/detail.aspx?dbname=CDFD2007\&filename=2007101113.nh\&dbcode=CDFD},
	date = {2007-03-01},
	journal = {电子科技大学},
	issue = {04},
	pages = {129-130},
	keywords = {空间功率合成技术;同轴波导;径向波导;基片集成波导;毫米波},
	doi = {CNKI:CDMD:1.2007.101113},
	typeofwork = {Null},
}
```
.net 已经表明这是学位论文 **{Reference Type}: Thesis**，但是转换的结果却是 **Misc**

**Comment by krisfans** [comment]
可能是源net文件缺少了`{Type of Work}: 博士
`这样的项目，只有`{Reference Type}: Thesis` ,而bib要区分`mastersthesis`和`phdthesis` 。但是希望如果缺省`{Type of Work}: 博士
`这一项，能映射到`mastersthesis`

**Comment by Vopaaz** [comment]
确实，实现中 `masterthesis` 的判断条件为 `[{"Reference Type": "Thesis", "Type of Work": "硕士"}]`, `phdthesis` 的判断条件为 `[{"Reference Type": "Thesis", "Type of Work": "博士"}]`，两项均需要满足，否则会转入托底的 `Misc`.

但是如果仅有 Reference Type 为 Thesis 这一项就默认为 `masterthesis`, 我个人感觉这种处理并不合理。`masterthesis` 和 `phdthesis` 之间并没有谁更适合作为默认值的区别，如果标记错误还是需要人为手动调整。因此我不会把这个 feature 放到公开的 build 里面。

你可以 fork 这个工程并且 apply https://github.com/Vopaaz/CNKI_2_BibTeX/commit/033d927458c90de3e9e645616552ffecabd9da29 这个 commit，就可以达到你想要的效果
